var1:
  unit: m/s
  style:
    - left: 50px
    - top: 250px
    - font-family: "Courier"

var2:
  unit: m/s
  style:
    - left: 250px
    - top: 250px
    - font-family: "Arial"
    - font-size: 250px
